/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ITracking, TSize } from "./types";
export namespace Components {
    interface ElementButton {
        /**
          * Visually and functionally disable the Button.
         */
        "disabled": boolean;
        /**
          * Visually disables the button and shows a loading spinner and also disables the button.
         */
        "isLoading": boolean;
        /**
          * Label as a string
         */
        "label": string;
        /**
          * Size of the button
         */
        "size": TSize;
        /**
          * Tracking data related to the `button`'s events
         */
        "tracking"?: ITracking;
        /**
          * Variant of the button
         */
        "variant": 'primary' | 'secondary';
    }
}
declare global {
    interface HTMLElementButtonElement extends Components.ElementButton, HTMLStencilElement {
    }
    var HTMLElementButtonElement: {
        prototype: HTMLElementButtonElement;
        new (): HTMLElementButtonElement;
    };
    interface HTMLElementTagNameMap {
        "element-button": HTMLElementButtonElement;
    }
}
declare namespace LocalJSX {
    interface ElementButton {
        /**
          * Visually and functionally disable the Button.
         */
        "disabled"?: boolean;
        /**
          * Visually disables the button and shows a loading spinner and also disables the button.
         */
        "isLoading"?: boolean;
        /**
          * Label as a string
         */
        "label"?: string;
        /**
          * Size of the button
         */
        "size"?: TSize;
        /**
          * Tracking data related to the `button`'s events
         */
        "tracking"?: ITracking;
        /**
          * Variant of the button
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface IntrinsicElements {
        "element-button": ElementButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "element-button": LocalJSX.ElementButton & JSXBase.HTMLAttributes<HTMLElementButtonElement>;
        }
    }
}
